// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Container: typeof import('./../../components/Container.vue')['default']
    Header: typeof import('./../../components/Header.vue')['default']
    IxButton: typeof import('@idux/components/button')['IxButton']
    IxDrawerProvider: typeof import('@idux/components/drawer')['IxDrawerProvider']
    IxMessageProvider: typeof import('@idux/components/message')['IxMessageProvider']
    IxModalProvider: typeof import('@idux/components/modal')['IxModalProvider']
    IxNotificationProvider: typeof import('@idux/components/notification')['IxNotificationProvider']
    IxSpace: typeof import('@idux/components/space')['IxSpace']
    IxSpin: typeof import('@idux/components/spin')['IxSpin']
  }
}

export { }
